### ISSUE TITLE
Interpreting alpha in phyloglm

### ISSUE THREAD

**Issue by Madeleinecg** [lamho86/phylolm#58]
Sorry this isn't an issue as such - I have just not been able to find an explanation anywhere.

I've used phylolm with an OU model of evolution before and understand how to interpret the alpha value for that.

How do I interpret the alpha in phyloglm? I assume it is quite different from the alpha in an OU model. In my current case, my model estimates an alpha of 4.94.

Many thanks

**Comment by lamho86** [comment]
Ives and Garland provide some guidelines on interpreting α of the phylogenetic logistic model in their paper: https://academic.oup.com/sysbio/article/59/1/9/1723322

For example, “For a given tree size and shape, the parameter α is associated with phylogenetic signal because the larger α, the greater the rate of transitions and hence the lower the phylogenetic correlations among species”.

In some sense, the explanation for α in this model is similar to the OU model. You also need to take into account the height of your tree.
