### ISSUE TITLE
Prediction accounting for phylogenetic

### ISSUE THREAD

**Issue by MorceletL** [lamho86/phylolm#70]
Hello everyone,

I'm new to phylolm, but I see so much potential to your work. Indeed, it can become a very powerfull tool to conduct analyse in ecology accounting for phylogenetics, and not genus or order as a random effect !

I've been trying to do trait imputation based on a model phylolm.  However, I can't find any information on how phylogenetic signal is accounted while doing prediction. My goal is to impute trait values for species with missing information while accounting for their phylogeny. Using the function predict() I don't know the variance-covariance matrix is accounted for or not. 

I hope you can understand my question, and help me to solve this issue !
Thanks
Lucile

**Comment by cecileane** [comment]
For trait imputation, you might want to look at [Rphylopars](https://github.com/ericgoolsby/Rphylopars/wiki) instead, which also uses the fast algorithm developed for `phylolm`. `Rphylopars` uses a correlation framework rather than regression, so it's great to use correlation between traits --in addition to phylogenetic correlation between species-- to do trait imputation.
